name: Build Jar Based

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.12"

      - name: Build with Gradle
        run: gradle clean build

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/distributions/*.zip
          retention-days: 2
          compression-level: 9
          if-no-files-found: error