name: Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Extract Gradle Version from Wrapper
        id: extract_gradle_version
        run: |
          VERSION=$(grep -oP 'gradle-\\K[0-9.]+' gradle/wrapper/gradle-wrapper.properties)
          echo "gradle_version=$VERSION" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.gradle_version }}

      - name: Build with Gradle
        run: gradle clean buildPlugin --no-daemon

      - name: Extract Version from build.gradle
        id: extract_version
        run: |
          VERSION=$(gradle -q printVersion)
          if [ -z "$VERSION" ]; then
            echo "Version not found."
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Latest Commit Info
        id: commit_message
        run: |
          echo "message=$(git log -1 --pretty=format:'- %s (%h)')" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/distributions/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          body: ${{ steps.commit_message.outputs.message }}
          draft: false
          prerelease: false
