name: Build Jar Based

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  # Ensure the workflow has permission to create releases and write to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.12"

      - name: Build with Gradle
        run: gradle clean build

      - name: Extract Version from build.gradle
        id: extract_version
        run: |
          VERSION=$(grep -oP "(?<=version ')[^']+" build.gradle)
          echo "##[set-output name=version;]v$VERSION"
      
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/distributions/*.zip
          retention-days: 2
          compression-level: 9
          if-no-files-found: error

      - name: Create Git Tag
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag -a "${{ steps.extract_version.outputs.version }}" -m "Release ${{ steps.extract_version.outputs.version }}"
          git push --tags

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
